export const heroPanels = [
  {
    id: 'amsterdam',
    img: 'https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?w=900&q=80&auto=format&fit=crop',
    alt: 'Amsterdam canal — Sandlip-Oasis European studio',
    flag: 'Europe — Amsterdam',
    title: ['Swiss ', 'Precision', '& Editorial Grace'],
    titleEm: 1,
    desc: 'Where typographic rigour meets refined minimalism. Our European studio sets the strategic and aesthetic foundation.',
  },
  {
    id: 'newyork',
    img: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=900&q=80&auto=format&fit=crop',
    alt: 'New York City skyline — Sandlip-Oasis American studio',
    flag: 'Americas — New York',
    title: ['Industrial ', 'Boldness', '& Raw Energy'],
    titleEm: 1,
    desc: 'Where creative ambition meets American scale. Our New York studio drives campaigns, digital, and cultural moments.',
  },
  {
    id: 'lagos',
    img: 'https://images.unsplash.com/photo-1618477388954-7852f32655ec?w=900&q=80&auto=format&fit=crop',
    alt: 'Lagos, Nigeria — Sandlip-Oasis African studio',
    flag: 'Africa — Lagos',
    title: ['Afro-Futurist ', 'Soul', '& Cultural Depth'],
    titleEm: 1,
    desc: "Where ancestral wisdom meets tomorrow's vision. Our Lagos studio brings cultural authenticity and geometric beauty.",
  },
]

export const workItems = [
  {
    id: 'ibukun',
    img: '/Images/Liz.jpeg',
    alt: 'Brand identity project for pan-African fintech startup',
    badge: 'Africa',
    badgeCls: 'badge-af',
    tag: 'Lagos · Brand Identity',
    title: 'Ìbúkún Financial Brand System',
  },
  {
    id: 'dekern',
    img: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=700&q=80&auto=format&fit=crop&crop=top',
    alt: 'European editorial fashion campaign, Amsterdam',
    badge: 'Europe',
    badgeCls: 'badge-eu',
    tag: 'Amsterdam · Campaign',
    title: 'De Kern Editorial Campaign',
  },
  {
    id: 'apex',
    img: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=700&q=80&auto=format&fit=crop&crop=top',
    alt: 'New York tech company rebrand project',
    badge: 'Americas',
    badgeCls: 'badge-us',
    tag: 'New York · Web',
    title: 'Apex Digital Platform',
  },
  {
    id: 'zikoko',
    img: 'https://images.unsplash.com/photo-1614644147798-f8c0fc9da7f6?w=700&q=80&auto=format&fit=crop',
    alt: 'Motion identity project for West African media company',
    badge: 'Africa',
    badgeCls: 'badge-af',
    tag: 'Lagos · Motion',
    title: 'Zikoko Motion Identity',
  },
  {
    id: 'maison',
    img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=700&q=80&auto=format&fit=crop',
    alt: 'Luxury brand design system for European fashion house',
    badge: 'Europe',
    badgeCls: 'badge-eu',
    tag: 'Amsterdam · Design System',
    title: 'Maison Volker Design System',
  },
]

export const offices = [
  {
    id: 'amsterdam',
    num: '01',
    city: 'Amsterdam',
    country: 'Netherlands — Europe',
    address: 'Herengracht 420, 1017 BZ',
    desc: 'Our European HQ. Home to brand strategy, editorial design, and the systematic precision that anchors every Sandlip-Oasis project.',
    img: 'https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?w=800&q=80&auto=format&fit=crop',
    alt: 'Amsterdam canals — Sandlip-Oasis European studio',
    flag: '🇳🇱',
    email: 'hello.ams@sandlip-oasis.com',
  },
  {
    id: 'newyork',
    num: '02',
    city: 'New York',
    country: 'USA — The Americas',
    address: '148 W 24th Street, NY 10011',
    desc: "Our American powerhouse. Web, product, campaigns, and cultural moments built for the world's most competitive market.",
    img: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800&q=80&auto=format&fit=crop',
    alt: 'New York City — Sandlip-Oasis American studio',
    flag: '🇺🇸',
    email: 'hello.nyc@sandlip-oasis.com',
  },
  {
    id: 'lagos',
    num: '03',
    city: 'Lagos',
    country: 'Nigeria — Africa',
    address: '14b Adeola Odeku, Victoria Island',
    desc: 'Our African soul. Afro-futurist identity design, motion, and campaign work rooted in the richest creative tradition on earth.',
    img: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?w=800&q=80&auto=format&fit=crop',
    alt: 'Lagos, Nigeria — Sandlip-Oasis African studio',
    flag: '🇳🇬',
    email: 'hello.lag@sandlip-oasis.com',
  },
]

export const team = [
  {
    id: 'john',
    img: '/Images/John.jpeg',
    alt: 'John Okeke, Co-founder and Creative Director, Lagos',
    continent: 'Lagos, Nigeria',
    name: 'Mr John Okeke',
    role: 'Co-founder · Creative Director',
    bio: '"Design is a language that speaks across borders. My mission is to ensure our African voice is heard clearly in the global creative conversation."',
  },
  {
    id: 'elizabeth',
    img: '/Images/Liz.jpeg',
    alt: 'Elizabeth, Co-founder and Strategy Director, Amsterdam',
    continent: 'Amsterdam, Netherlands',
    name: 'Elizabeth',
    role: 'Co-founder · Strategy Director',
    bio: '"True strategy is about finding the common thread in diverse perspectives. We build bridges between cultures through thoughtful, systematic design."',
  },
  {
    id: 'james',
    img: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=700&q=80&auto=format&fit=crop&crop=top',
    alt: 'James Carter, Co-founder and Film Director, New York',
    continent: 'New York, USA',
    name: 'James Carter',
    role: 'Co-founder · Film Director',
    bio: '"A brand film should feel like a memory you haven\'t had yet. That\'s what we\'re chasing every time we pick up a camera."',
  },
  {
    id: 'favour',
    img: '/Images/Favour.png',
    alt: 'Favour Isecap, Head of Design, Lagos',
    continent: 'Lagos, Nigeria',
    name: 'Favour Isecap',
    role: 'Head of Design · Lagos',
    bio: '"The future of design is about inclusivity and cultural depth. I strive to create work that resonates on a human level, across every continent."',
  },
  {
    id: 'marcus',
    img: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=700&q=80&auto=format&fit=crop&crop=top',
    alt: 'Marcus Webb, Head of Technology, New York',
    continent: 'New York, USA',
    name: 'Marcus Webb',
    role: 'Head of Technology · New York',
    bio: '"The best-designed product is invisible. You feel it working — you never notice it straining. That\'s the standard we build to."',
  },
  {
    id: 'linh',
    img: 'https://images.unsplash.com/photo-1573497161161-c3e73707e25c?w=700&q=80&auto=format&fit=crop&crop=top',
    alt: 'Linh Nguyen, Senior Designer, Amsterdam',
    continent: 'Amsterdam, Netherlands',
    name: 'Linh Nguyen',
    role: 'Senior Designer · Amsterdam',
    bio: '"Design that doesn\'t question its assumptions is just decoration. Every project starts with an uncomfortable question."',
  },
]

export const services = [
  {
    num: '01',
    title: 'Brand Identity',
    desc: 'Visual systems built from multiple cultural traditions. Swiss precision, Afro-geometric pattern, American scale.',
    tags: ['Strategy', 'Logo', 'Type', 'Pattern'],
  },
  {
    num: '02',
    title: 'Web & Product Design',
    desc: 'Digital products designed for global reach — fast in Lagos, beautiful in Amsterdam, conversion-optimised in New York.',
    tags: ['UI/UX', 'React', 'Figma', 'Next.js'],
  },
  {
    num: '03',
    title: 'Campaign Creative',
    desc: 'Integrated campaigns that understand multiple markets simultaneously. Not translated — genuinely localised.',
    tags: ['OOH', 'Digital', 'Print', 'Social'],
  },
  {
    num: '04',
    title: 'Motion & Film',
    desc: 'Brand films, motion identity, social video. Cinematic quality from New York. Cultural depth from Lagos. Editorial beauty from Amsterdam.',
    tags: ['Film', 'Animation', 'GSAP', 'Lottie'],
  },
  {
    num: '05',
    title: 'Design Systems',
    desc: 'Scalable component libraries and design tokens built for global product teams. Multi-directional, multi-cultural from day one.',
    tags: ['Tokens', 'Components', 'Docs'],
  },
  {
    num: '06',
    title: 'Global Retainer',
    desc: 'Embedded creative partnership across one, two, or all three studios. Dedicated senior hours, strategic access, priority turnaround.',
    tags: ['Monthly', 'Priority', 'Multi-studio'],
  },
]

export const processSteps = [
  {
    num: '01',
    label: 'Listen',
    title: 'Deep Discovery',
    desc: 'Three studios. Three perspectives on your brief. We spend more time in the discovery phase than most agencies spend on the entire project.',
  },
  {
    num: '02',
    label: 'Define',
    title: 'Aligned Strategy',
    desc: 'One unified brief, co-written across studios. Creative direction that all three offices commit to before a single pixel moves.',
  },
  {
    num: '03',
    label: 'Create',
    title: 'Parallel Creation',
    desc: 'Studios work in parallel, informed by each other. Weekly cross-continental reviews. The friction is built in — and that\'s where the magic lives.',
  },
  {
    num: '04',
    label: 'Launch',
    title: 'Global Delivery',
    desc: 'QA and handoff across all markets simultaneously. Launch support in every timezone. We stay until it works everywhere.',
  },
]

export const testimonials = [
  {
    id: 't1',
    quote: "Sandlip-Oasis didn't just give us a brand. They gave us a position — rooted in our Nigerian identity but capable of walking into any boardroom on earth.",
    name: 'Adaeze Okonkwo',
    role: 'CEO · Ìbúkún Financial, Lagos',
    continent: 'Lagos, Nigeria',
    img: 'https://images.unsplash.com/photo-1589156229687-496a31ad1d1f?w=200&q=80&auto=format&fit=crop&crop=face',
  },
  {
    id: 't2',
    quote: 'Every agency we interviewed had a portfolio. Sandlip-Oasis had a point of view. Their New York and Amsterdam teams collaborated on our rebrand in real time. It was remarkable.',
    name: 'Marcus Reid',
    role: 'CEO · TechRidge, New York',
    continent: 'New York, USA',
    img: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80&auto=format&fit=crop&crop=face',
  },
  {
    id: 't3',
    quote: 'The Amsterdam team understood our Dutch heritage with precision. The Lagos team gave us a pattern system that referenced Kente cloth. The fusion was extraordinary.',
    name: 'Eva de Groot',
    role: 'Brand Director · Maison Volker, Amsterdam',
    continent: 'Amsterdam, NL',
    img: 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=200&q=80&auto=format&fit=crop&crop=face',
  },
  {
    id: 't4',
    quote: 'Working with Sandlip-Oasis across three time zones felt seamless. One consistent creative voice, three different cultural perspectives. Genuinely unlike anything we had seen.',
    name: 'Sophia Mensah',
    role: 'CMO · Globalink Ventures, London',
    continent: 'Global',
    img: 'https://images.unsplash.com/photo-1573497161161-c3e73707e25c?w=200&q=80&auto=format&fit=crop&crop=face',
  },
]

export const journalPosts = [
  {
    id: 'collision',
    featured: true,
    cat: 'Cross-Cultural Design',
    title: 'What happens when three visual traditions collide in a single logo?',
    desc: 'We documented the 12-week process of building a unified brand identity for a client with offices in Amsterdam, Lagos, and Chicago. The compromises. The fights. The breakthrough.',
    date: 'May 2025',
    img: 'https://images.unsplash.com/photo-1542744094-3a31f272c490?w=900&q=80&auto=format&fit=crop',
    alt: 'African creative professional working on cross-cultural design project',
  },
  {
    id: 'dutch',
    featured: false,
    cat: 'Amsterdam — Branding',
    title: 'Why Dutch design still leads the world in systematic thinking',
    desc: 'The Werkman legacy. Total Design. Wim Crouwel. How Dutch traditions quietly underpin half the design systems running in Silicon Valley right now.',
    date: 'Apr 2025',
    img: 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=700&q=80&auto=format&fit=crop',
    alt: 'Amsterdam canal and architecture — European design culture',
  },
  {
    id: 'global-branding',
    featured: false,
    cat: 'Global — Strategy',
    title: 'Beyond Translation: The Art of Global Branding',
    desc: "Why simply translating your message isn't enough for the African or European markets. We look at the cultural nuances that make or break a brand launch.",
    date: 'May 2025',
    img: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=700&q=80&auto=format&fit=crop',
    alt: 'Sandlip-Oasis global strategy session',
  },
  {
    id: 'performance',
    featured: false,
    cat: 'New York — Digital',
    title: "The performance gap that's costing American brands African customers",
    desc: '85% of African internet traffic is mobile. Most US-designed products fail in that environment. Here\'s the fix — and why it makes your product better everywhere.',
    date: 'Mar 2025',
    img: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=700&q=80&auto=format&fit=crop',
    alt: 'New York creative team meeting',
  },
  {
    id: 'ankara',
    featured: false,
    cat: 'Lagos — Design Systems',
    title: "Ankara patterns are the world's oldest design token system",
    desc: 'Before Figma, before Style Dictionary, Yoruba weavers were encoding meaning into repeating visual systems. The implications for modern design are enormous.',
    date: 'Feb 2025',
    img: 'https://images.unsplash.com/photo-1590735213920-68192a487bc2?w=700&q=80&auto=format&fit=crop',
    alt: 'Ankara fabric geometric pattern — African design systems',
  },
  {
    id: 'timezones',
    featured: false,
    cat: 'Global — UX',
    title: "Designing for three time zones at once: what we've actually learned",
    desc: 'After 11 years of cross-continental collaboration, here are the practical workflows, tools, and cultural protocols that make Sandlip-Oasis function as one studio.',
    date: 'Jan 2025',
    img: 'https://images.unsplash.com/photo-1573497620053-ea5300f94f21?w=700&q=80&auto=format&fit=crop',
    alt: 'African woman UX designer testing mobile application',
  },
  {
    id: 'brief',
    featured: false,
    cat: 'Global — Strategy',
    title: 'The brief that changed how we think about global creative work',
    desc: 'In 2021 a client asked us to build one brand that could live equally authentically in London, Lagos, and Los Angeles. Here\'s what we got wrong — and what we eventually got right.',
    date: 'Dec 2024',
    img: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=700&q=80&auto=format&fit=crop',
    alt: 'Sandlip-Oasis cross-continental team strategy presentation',
  },
]

export const photoStrip = [
  { img: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=500&q=80&auto=format&fit=crop', alt: 'Sandlip-Oasis creative team in Lagos studio' },
  { img: 'https://images.unsplash.com/photo-1542744094-3a31f272c490?w=500&q=80&auto=format&fit=crop', alt: 'Brand designer sketching concepts in Amsterdam' },
  { img: 'https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?w=500&q=80&auto=format&fit=crop', alt: 'New York Sandlip-Oasis office and team collaboration' },
  { img: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=500&q=80&auto=format&fit=crop', alt: 'Diverse Sandlip-Oasis team celebrating project launch' },
  { img: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=500&q=80&auto=format&fit=crop', alt: 'Sandlip-Oasis global strategy session across time zones' },
]
